#!/usr/bin/env bash

BUCKET_NAME="$1"

if [ -z "$BUCKET_NAME" ]; then
  echo "Error: please provide a bucket name. Usage: ./create-object <bucket-name>"
  exit 1
fi

aws s3api create-bucket --bucket "$BUCKET_NAME"
