#!/usr/bin/env bash

BUCKET_NAME="$1"

if [ -z "$BUCKET_NAME" ]; then
  echo "Error: please provide a bucket name. Usage: ./list-objects <bucket-name>"
  exit 1
fi

aws s3api list-objects-v2 --bucket "$BUCKET_NAME"